import MathTools               from './studios/MathTools'
import CSTools                 from './studios/CSTools'
import PhilosophyTools         from './studios/PhilosophyTools'
import ScienceTools            from './studios/ScienceTools'
import LiteratureTools         from './studios/LiteratureTools'
import HistoryTools            from './studios/HistoryTools'
import ArtsTools               from './studios/ArtsTools'
import AccountingTools         from './studios/AccountingTools'
import EconomicsTools          from './studios/EconomicsTools'
import MathCalculatorTools     from './studios/MathCalculatorTools'
import AccountingFormulasTools from './studios/AccountingFormulasTools'

const STUDIO_CONFIGS = {
  mathematics: {
    id:            'mathematics',
    name:          'Mathematics',
    icon:          '∑',
    color:         '#4a9eca',
    subtitle:      'Pure & Applied Mathematics',
    heroTitle:     ['Master the Language', 'of the Universe'],
    heroSub:       'From calculus to statistics — explore formulas, convert units, and build intuition across every branch of mathematics.',
    storagePrefix: 'mls_math',
    subjects:      ['Calculus', 'Linear Algebra', 'Statistics', 'Discrete Mathematics', 'Number Theory', 'Other'],
    navLinks:      [['tools','🧮 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful mathematics tutor inside "Mogul\'s Learning Studio". Assist with calculus, algebra, statistics, linear algebra, discrete mathematics, and all levels of mathematics. Give clear step-by-step explanations, show working, and use examples. When writing formulas, use clear notation. Keep answers educational and structured.',
    ToolsComponent: MathTools,
  },
  cs: {
    id:            'cs',
    name:          'Computer Science',
    icon:          '⌨',
    color:         '#6e8efb',
    subtitle:      'Programming & Algorithms',
    heroTitle:     ['Think Computationally,', 'Build Brilliantly'],
    heroSub:       'Big-O complexity, data structures, base conversion, and algorithm analysis — the CS toolkit for serious problem-solvers.',
    storagePrefix: 'mls_cs',
    subjects:      ['Algorithms', 'Data Structures', 'Operating Systems', 'Databases', 'Networks', 'Software Engineering', 'Other'],
    navLinks:      [['tools','💻 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful computer science tutor inside "Mogul\'s Learning Studio". Assist with algorithms, data structures, complexity analysis, programming concepts, software engineering, databases, networks, and operating systems. Provide clear explanations, pseudocode or code examples where helpful, and break down complex concepts systematically.',
    ToolsComponent: CSTools,
  },
  philosophy: {
    id:            'philosophy',
    name:          'Philosophy',
    icon:          '⚖',
    color:         '#9b7fd4',
    subtitle:      'Ethics, Logic & Metaphysics',
    heroTitle:     ['Question Everything,', 'Know Thyself'],
    heroSub:       'Explore great thinkers, map arguments with formal logic, and engage in Socratic dialogue on the deepest questions of existence.',
    storagePrefix: 'mls_phil',
    subjects:      ['Ethics', 'Logic', 'Epistemology', 'Metaphysics', 'Political Philosophy', 'Aesthetics', 'Other'],
    navLinks:      [['tools','⚖ Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful philosophy tutor inside "Mogul\'s Learning Studio". Assist with ethics, logic, epistemology, metaphysics, political philosophy, and the history of philosophy. Engage with ideas rigorously, present multiple perspectives, use the Socratic method where appropriate, and explain philosophical arguments clearly with examples.',
    ToolsComponent: PhilosophyTools,
  },
  sciences: {
    id:            'sciences',
    name:          'Natural Sciences',
    icon:          '🔬',
    color:         '#2ecc71',
    subtitle:      'Physics, Chemistry & Biology',
    heroTitle:     ['Observe, Hypothesise,', 'Discover'],
    heroSub:       'Explore the periodic table, convert SI units, and apply the scientific method across physics, chemistry, and biology.',
    storagePrefix: 'mls_sci',
    subjects:      ['Physics', 'Chemistry', 'Biology', 'Environmental Science', 'Earth Science', 'Other'],
    navLinks:      [['tools','🔬 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful natural sciences tutor inside "Mogul\'s Learning Studio". Assist with physics, chemistry, biology, earth sciences, and environmental science. Explain concepts clearly using scientific language and real-world examples. Show calculations step-by-step, explain experimental design, and help students understand the scientific method.',
    ToolsComponent: ScienceTools,
  },
  literature: {
    id:            'literature',
    name:          'Literature',
    icon:          '📖',
    color:         '#e8a84c',
    subtitle:      'Language & Literary Analysis',
    heroTitle:     ['Read Deeply,', 'Write Powerfully'],
    heroSub:       'Track your reading, master literary devices, plan essays, and develop your critical voice as a reader and writer.',
    storagePrefix: 'mls_lit',
    subjects:      ['Literary Analysis', 'Essay Writing', 'Poetry', 'Drama', 'Postcolonial Literature', 'Creative Writing', 'Other'],
    navLinks:      [['tools','📖 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful literature and writing tutor inside "Mogul\'s Learning Studio". Assist with literary analysis, essay writing, close reading, understanding literary devices, poetry, drama, and rhetoric. Help students develop their critical voice, structure arguments, analyse texts in depth, and improve their writing style and technique.',
    ToolsComponent: LiteratureTools,
  },
  history: {
    id:            'history',
    name:          'History & Politics',
    icon:          '🌍',
    color:         '#cd6155',
    subtitle:      'Past Events & Global Affairs',
    heroTitle:     ['Those Who Forget History', 'Are Doomed to Repeat It'],
    heroSub:       'Build personal timelines, study key historical figures, and develop sharp analytical thinking about world events and political systems.',
    storagePrefix: 'mls_hist',
    subjects:      ['World History', 'Political Theory', 'Geopolitics', 'Economic History', 'Social History', 'Historiography', 'Other'],
    navLinks:      [['tools','🌍 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful history and politics tutor inside "Mogul\'s Learning Studio". Assist with world history, political theory, geopolitics, economic history, historiography, and current affairs. Provide balanced, nuanced analysis of events and ideologies. Help students think historically, understand causation and consequence, and develop well-structured arguments.',
    ToolsComponent: HistoryTools,
  },
  arts: {
    id:            'arts',
    name:          'Arts & Design',
    icon:          '🎨',
    color:         '#e74c8b',
    subtitle:      'Creative & Visual Studies',
    heroTitle:     ['Create with Intention,', 'Design with Purpose'],
    heroSub:       'Track creative projects, explore colour theory, master design principles, and build a portfolio that speaks for itself.',
    storagePrefix: 'mls_arts',
    subjects:      ['Visual Art', 'Graphic Design', 'UX/UI Design', 'Photography', 'Art History', 'Architecture', 'Other'],
    navLinks:      [['tools','🎨 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful arts and design tutor inside "Mogul\'s Learning Studio". Assist with visual art, graphic design, UX/UI design, art history, photography, typography, colour theory, and design principles. Provide thoughtful creative guidance, explain design concepts clearly, and help students develop their aesthetic sensibility and critical eye.',
    ToolsComponent: ArtsTools,
  },
  accounting: {
    id:            'accounting',
    name:          'Accounting',
    icon:          '📒',
    color:         '#27ae60',
    subtitle:      'Financial Reporting & Analysis',
    heroTitle:     ['Balance the Books,', 'Master the Numbers'],
    heroSub:       'Financial ratios, depreciation schedules, break-even analysis, and journal entry builder — everything you need to excel in accounting.',
    storagePrefix: 'mls_acct',
    subjects:      ['Financial Accounting', 'Management Accounting', 'Auditing', 'Taxation', 'Cost Accounting', 'Other'],
    navLinks:      [['tools','📒 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful accounting tutor inside "Mogul\'s Learning Studio". Assist with financial accounting, management accounting, auditing, taxation, cost accounting, and financial reporting. Explain double-entry bookkeeping, financial statements, ratio analysis, and costing methods clearly with worked examples. Follow IFRS/IAS standards where applicable.',
    ToolsComponent: AccountingTools,
  },
  economics: {
    id:            'economics',
    name:          'Economics',
    icon:          '📈',
    color:         '#f39c12',
    subtitle:      'Micro & Macroeconomics',
    heroTitle:     ['Understand Markets,', 'Shape Policy'],
    heroSub:       'GDP, elasticity, market equilibrium, fiscal multipliers — your complete economics toolkit for micro and macro analysis.',
    storagePrefix: 'mls_econ',
    subjects:      ['Microeconomics', 'Macroeconomics', 'International Economics', 'Development Economics', 'Econometrics', 'Other'],
    navLinks:      [['tools','📈 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful economics tutor inside "Mogul\'s Learning Studio". Assist with microeconomics, macroeconomics, international trade, development economics, and econometrics. Explain supply and demand, market structures, GDP, inflation, fiscal and monetary policy, and elasticity clearly. Use diagrams, real-world examples, and structured explanations.',
    ToolsComponent: EconomicsTools,
  },
  mathcalc: {
    id:            'mathcalc',
    name:          'Math Calculator',
    icon:          '🧮',
    color:         '#3498db',
    subtitle:      'Scientific Calculator & Solvers',
    heroTitle:     ['Calculate with Precision,', 'Solve with Confidence'],
    heroSub:       'Full scientific calculator, equation solver (quadratic, simultaneous, cubic), and sequence generator — the mathematician\'s power toolkit.',
    storagePrefix: 'mls_calc',
    subjects:      ['Calculus', 'Algebra', 'Statistics', 'Pure Mathematics', 'Applied Mathematics', 'Other'],
    navLinks:      [['tools','🧮 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful mathematics calculator assistant inside "Mogul\'s Learning Studio". Help users understand how to use scientific calculators, solve equations algebraically and numerically, work with sequences and series, and apply mathematical concepts. Show step-by-step working for all calculations and explain the underlying theory.',
    ToolsComponent: MathCalculatorTools,
  },
  accountingformulas: {
    id:            'accountingformulas',
    name:          'Accounting Formulas',
    icon:          '📐',
    color:         '#1abc9c',
    subtitle:      'Formulas, Ratios & Statement Builder',
    heroTitle:     ['Every Formula', 'at Your Fingertips'],
    heroSub:       '30+ accounting formulas, a comprehensive ratio calculator across all 5 ratio groups, and an interactive income statement & balance sheet builder.',
    storagePrefix: 'mls_acctf',
    subjects:      ['Financial Ratios', 'Financial Statements', 'Valuation', 'Depreciation', 'Inventory', 'Other'],
    navLinks:      [['tools','📐 Tools'], ['tasks','✅ Tasks'], ['pomodoro','🍅 Timer'], ['grades','🎓 Grades'], ['materials','📚 Files'], ['notes','📓 Notes'], ['flashcards','🃏 Flashcards'], ['quiz','📝 Quiz'], ['exams','📅 Exams'], ['syllabus','📋 Syllabus'], ['schedule','🗓 Schedule'], ['trends','📈 Trends'], ['reading','📖 Reading'], ['mindmap','🧠 Mind Map'], ['citations','🔖 Citations'], ['attendance','✅ Attendance'], ['ai','AI ✦']],
    aiSystemPrompt: 'You are a helpful financial accounting formulas assistant inside "Mogul\'s Learning Studio". Help users understand and apply accounting formulas, ratio analysis, financial statement construction, and valuation methods. Explain what each ratio means, what benchmarks indicate good performance, and how financial statements connect to each other. Follow IFRS standards.',
    ToolsComponent: AccountingFormulasTools,
  },
}

export default STUDIO_CONFIGS
